### ISSUE TITLE
Severe Mouse Delay

### ISSUE THREAD

**Issue by lastpeony** [ant-media/TunaDesk#4]
It appears that the mouse is lagging, which may be attributed to the data being transferred via reliable SCTP data channels. To address this issue, a potential solution is to establish separate data channels specifically dedicated to mouse movement data, using an unreliable transmission mechanism.

By implementing separate data channels that prioritize speed over reliability, we can optimize the transmission of mouse movement data, potentially reducing the lag experienced. This approach should improve the responsiveness and overall performance of the mouse.

**Comment by mustafaboleken** [comment]
For now, until [Cursor visibility supported](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/cursor), we just hide cursor on controller's page in full screen mode.
